name: Publish Package

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  publish-npm:
    name: Publish to NPM
    if: github.repository_owner == 'd0rich'
    outputs:
      version: ${{ steps.publish.outputs.version }}
      type: ${{ steps.publish.outputs.type }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: JS-DevTools/npm-publish@v1
        id: publish
        with:
          access: public
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: [publish-npm]
    if: needs.publish-npm.outputs.type != 'none'
    steps:
      - uses: actions/checkout@v3

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1
        with:
          diff-search: true

      - uses: rickstaa/action-create-tag@v1
        if: steps.check.outputs.changed == 'true'
        with:
          tag: 'v${{ needs.publish-npm.outputs.version }}'

      - name: Create Release
        if: steps.check.outputs.changed == 'true'
        uses: ncipollo/release-action@v1
        with:
          tag: 'v${{ needs.publish-npm.outputs.version }}'
          generateReleaseNotes: true
          draft: false

