name: Publish Package

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.check.outputs.changed }}
    steps:
      - uses: actions/checkout@v3

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1
        with:
          diff-search: true

      - uses: rickstaa/action-create-tag@v1
        if: steps.check.outputs.changed == 'true'
        with:
          tag: 'v${{ steps.check.outputs.version }}'

      - name: Create Release
        if: steps.check.outputs.changed == 'true'
        uses: ncipollo/release-action@v1
        with:
          tag: 'v${{ steps.check.outputs.version }}'
          generateReleaseNotes: true
          draft: false

  publish-npm:
    name: Publish to NPM
    needs: [release]
    if: (needs.release.outputs.version_changed == 'true') && (github.repository_owner == 'd0rich')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
